// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_pty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_pty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_pty_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *TerminalSize          `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_pty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_pty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_pty_proto_rawDescGZIP(), []int{1}
}

func (x *Start) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type PtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*PtyRequest_Start
	//	*PtyRequest_Input
	//	*PtyRequest_Resize
	Event         isPtyRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyRequest) Reset() {
	*x = PtyRequest{}
	mi := &file_pty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyRequest) ProtoMessage() {}

func (x *PtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyRequest.ProtoReflect.Descriptor instead.
func (*PtyRequest) Descriptor() ([]byte, []int) {
	return file_pty_proto_rawDescGZIP(), []int{2}
}

func (x *PtyRequest) GetEvent() isPtyRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PtyRequest) GetStart() *Start {
	if x != nil {
		if x, ok := x.Event.(*PtyRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *PtyRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Event.(*PtyRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PtyRequest) GetResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Event.(*PtyRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isPtyRequest_Event interface {
	isPtyRequest_Event()
}

type PtyRequest_Start struct {
	Start *Start `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type PtyRequest_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type PtyRequest_Resize struct {
	Resize *TerminalSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*PtyRequest_Start) isPtyRequest_Event() {}

func (*PtyRequest_Input) isPtyRequest_Event() {}

func (*PtyRequest_Resize) isPtyRequest_Event() {}

type PtyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*PtyResponse_Output
	//	*PtyResponse_ExitCode
	Event         isPtyResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyResponse) Reset() {
	*x = PtyResponse{}
	mi := &file_pty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyResponse) ProtoMessage() {}

func (x *PtyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyResponse.ProtoReflect.Descriptor instead.
func (*PtyResponse) Descriptor() ([]byte, []int) {
	return file_pty_proto_rawDescGZIP(), []int{3}
}

func (x *PtyResponse) GetEvent() isPtyResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PtyResponse) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Event.(*PtyResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *PtyResponse) GetExitCode() uint32 {
	if x != nil {
		if x, ok := x.Event.(*PtyResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isPtyResponse_Event interface {
	isPtyResponse_Event()
}

type PtyResponse_Output struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type PtyResponse_ExitCode struct {
	ExitCode uint32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*PtyResponse_Output) isPtyResponse_Event() {}

func (*PtyResponse_ExitCode) isPtyResponse_Event() {}

var File_pty_proto protoreflect.FileDescriptor

const file_pty_proto_rawDesc = "" +
	"\n" +
	"\tpty.proto\x12\x03pty\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\".\n" +
	"\x05Start\x12%\n" +
	"\x04size\x18\x03 \x01(\v2\x11.pty.TerminalSizeR\x04size\"~\n" +
	"\n" +
	"PtyRequest\x12\"\n" +
	"\x05start\x18\x01 \x01(\v2\n" +
	".pty.StartH\x00R\x05start\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.pty.TerminalSizeH\x00R\x06resizeB\a\n" +
	"\x05event\"O\n" +
	"\vPtyResponse\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\rH\x00R\bexitCodeB\a\n" +
	"\x05event29\n" +
	"\x03Pty\x122\n" +
	"\aSession\x12\x0f.pty.PtyRequest\x1a\x10.pty.PtyResponse\"\x00(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_pty_proto_rawDescOnce sync.Once
	file_pty_proto_rawDescData []byte
)

func file_pty_proto_rawDescGZIP() []byte {
	file_pty_proto_rawDescOnce.Do(func() {
		file_pty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pty_proto_rawDesc), len(file_pty_proto_rawDesc)))
	})
	return file_pty_proto_rawDescData
}

var file_pty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pty_proto_goTypes = []any{
	(*TerminalSize)(nil), // 0: pty.TerminalSize
	(*Start)(nil),        // 1: pty.Start
	(*PtyRequest)(nil),   // 2: pty.PtyRequest
	(*PtyResponse)(nil),  // 3: pty.PtyResponse
}
var file_pty_proto_depIdxs = []int32{
	0, // 0: pty.Start.size:type_name -> pty.TerminalSize
	1, // 1: pty.PtyRequest.start:type_name -> pty.Start
	0, // 2: pty.PtyRequest.resize:type_name -> pty.TerminalSize
	2, // 3: pty.Pty.Session:input_type -> pty.PtyRequest
	3, // 4: pty.Pty.Session:output_type -> pty.PtyResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pty_proto_init() }
func file_pty_proto_init() {
	if File_pty_proto != nil {
		return
	}
	file_pty_proto_msgTypes[2].OneofWrappers = []any{
		(*PtyRequest_Start)(nil),
		(*PtyRequest_Input)(nil),
		(*PtyRequest_Resize)(nil),
	}
	file_pty_proto_msgTypes[3].OneofWrappers = []any{
		(*PtyResponse_Output)(nil),
		(*PtyResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pty_proto_rawDesc), len(file_pty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pty_proto_goTypes,
		DependencyIndexes: file_pty_proto_depIdxs,
		MessageInfos:      file_pty_proto_msgTypes,
	}.Build()
	File_pty_proto = out.File
	file_pty_proto_goTypes = nil
	file_pty_proto_depIdxs = nil
}
