// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: pty.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pty_Session_FullMethodName = "/pty.Pty/Session"
)

// PtyClient is the client API for Pty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtyClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PtyRequest, PtyResponse], error)
}

type ptyClient struct {
	cc grpc.ClientConnInterface
}

func NewPtyClient(cc grpc.ClientConnInterface) PtyClient {
	return &ptyClient{cc}
}

func (c *ptyClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PtyRequest, PtyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Pty_ServiceDesc.Streams[0], Pty_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PtyRequest, PtyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pty_SessionClient = grpc.BidiStreamingClient[PtyRequest, PtyResponse]

// PtyServer is the server API for Pty service.
// All implementations must embed UnimplementedPtyServer
// for forward compatibility.
type PtyServer interface {
	Session(grpc.BidiStreamingServer[PtyRequest, PtyResponse]) error
	mustEmbedUnimplementedPtyServer()
}

// UnimplementedPtyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPtyServer struct{}

func (UnimplementedPtyServer) Session(grpc.BidiStreamingServer[PtyRequest, PtyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedPtyServer) mustEmbedUnimplementedPtyServer() {}
func (UnimplementedPtyServer) testEmbeddedByValue()             {}

// UnsafePtyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtyServer will
// result in compilation errors.
type UnsafePtyServer interface {
	mustEmbedUnimplementedPtyServer()
}

func RegisterPtyServer(s grpc.ServiceRegistrar, srv PtyServer) {
	// If the following call pancis, it indicates UnimplementedPtyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pty_ServiceDesc, srv)
}

func _Pty_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PtyServer).Session(&grpc.GenericServerStream[PtyRequest, PtyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pty_SessionServer = grpc.BidiStreamingServer[PtyRequest, PtyResponse]

// Pty_ServiceDesc is the grpc.ServiceDesc for Pty service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pty_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pty.Pty",
	HandlerType: (*PtyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Pty_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pty.proto",
}
